### ISSUE TITLE
Переменные содержащие списки

### ISSUE THREAD

**Issue by kamilov** [Infinitiweb/php-code-conventions#5]
[В названии переменной не должно быть указания типа](https://github.com/Infinitiweb/php-code-conventions/blob/master/README.md#-%D0%92-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9-%D0%BD%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE-%D0%B1%D1%8B%D1%82%D1%8C-%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D0%B8%D0%BF%D0%B0)

Про форматы оставляем, а вот со списками работаем следующим образом:
- В названии переменной в начале стоит название сущности в единственном числе
- На конце прописывается List

Плохо:

```php
$projects = [];
$usersList = [];
```

Хорошо:

```php
$pojectList = [];
$userList = [];
```

**Comment by hello-omny** [comment]
Я за оба варианта использования, `$projects` и `$pojectList` вполне себе ок.

**Comment by hello-omny** [comment]
> Нужно определиться с чем-то одним

Я вижу профит в обоих, и они друг друга не отменяют.
`$projects` — меньше времени набирать, смысловая нагрузка в принципе однозначна — список проектов.
`$pojectList` — набирать долше, но, например в фориче меньше путаницы, по смыслу тоже однозначно понимаешь, что в переменной хранится.

**Comment by rzhukovskiy** [comment]
Я за List и унификацию. Поэтому оставляем List
