### ISSUE TITLE
Подстановка переменных в строку

### ISSUE THREAD

**Issue by kamilov** [Infinitiweb/php-code-conventions#7]
[Вместо лишней конкатенации используем подстановку переменных в двойных кавычках](https://github.com/Infinitiweb/php-code-conventions/blob/master/README.md#-%D0%92%D0%BC%D0%B5%D1%81%D1%82%D0%BE-%D0%BB%D0%B8%D1%88%D0%BD%D0%B5%D0%B9-%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0%D1%82%D0%B5%D0%BD%D0%B0%D1%86%D0%B8%D0%B8-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D0%BC-%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D1%83-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-%D0%B4%D0%B2%D0%BE%D0%B9%D0%BD%D1%8B%D1%85-%D0%BA%D0%B0%D0%B2%D1%8B%D1%87%D0%BA%D0%B0%D1%85)

Так же хорошо будет использовать функцию **sprintf**

Хорошо:

```php
$string = sprintf(
    'Object with type "%s" has been removed', // шаблон
    $object->type()
);
```

**Comment by hello-omny** [comment]
[024db1a](https://github.com/Infinitiweb/php-code-conventions/commit/024db1a6aa8d2d676ad59efea1dcc1924da5c54b)
